---
- name: Prueba con fichero
  hosts: apache
  tasks:
  - name: Mandar un fichero
    ansible.builtin.copy:
      src: /home/usuSemaphore/archivo.txt
      dest: /tmp/archivoSemaphore.txt
      owner: usuGenerico
      group: usuGenerico
      mode: '0644'
